### ISSUE TITLE
failed to run covimerage

### ISSUE THREAD

**Issue by wsdjeg** [Vimjas/covimerage#98] opened 2021-08-11 03:51 UTC
when run `covimerage run nvim -Nu test/vimrc -c 'Vader! test/**'` in github action, I got:

**nvim v0.5.0:**

```
bundle/ale/ale_linters/go/gofmt.vim                                                                       10     10     0%
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/cli.py", line 192, in run
    **report_opts)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/cli.py", line 278, in report
    skip_covered=skip_covered,
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/coveragepy.py", line 71, in wrapper
    return f(*args, **kwargs)
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/coveragepy.py", line 129, in report
    omit=omit, skip_covered=skip_covered)
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/control.py", line 1041, in report
    return reporter.report(morfs, outfile=file)
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/summary.py", line 143, in report
    writeout(line[0])
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/summary.py", line 35, in writeout
    outfile.write(line.rstrip())
BlockingIOError: [Errno 11] write could not complete without blocking
bundle/ale/ale_linters/go/golangci_lint.vim                                                               39     39     0%
bundle/ale/ale_linters/go/golint.vim                                                                      14     14     0%
bundle/ale/ale_linters/go/gometalinter.vim                                                                39     39     0%
bundle/ale/ale_linters/go/gopls.vim                                                                       22     22     0%
bundle/ale/ale_linters/go/gosimple.vim                                                                    11     11     0%
bundle/ale/ale_linters/go/gotype.vim                                                                      13     13     0%
bundle/ale/ale_linters/go/govet.vim                                                                       18     18     0%
bundle/ale/ale_linters/go/langserver.vim                                                                  19     19     0%
bundle/ale/ale_linters/go/revive.vim                                                                      14     14     0%
bundle/ale/ale_linters/go/staticcheck.vim                                                                 23     23     0%
bundle/ale/ale_linters/graphql/eslint.vim                                                                  6      6     0%
bundle/ale/ale_linters/graphql/gqlint.vim                                                                 10     10     0%
bundle/ale/ale_linters/hack/hack.vim                                                                      13     13     0%
bundle/ale/ale_linters/hack/hhast.vim                                                                     23     23     0%
bundle/ale/ale_linters/haml/hamllint.vim                                                                  32     32     0%
bundle/ale/ale_linters/handlebars/embertemplatelint.vim                                                   43     43     0%
bundle/ale/ale_linters/haskell/cabal_ghc.vim                                                              14     14     0%
bundle/ale/ale_linters/haskell/ghc.vim                                                                    12     12     0%
bundle/ale/ale_linters/haskell/ghc_mod.vim                                                                12     12     0%
bundle/ale/ale_linters/haskell/hdevtools.vim                                                              13     13     0%
make: *** [test_coverage] Error 1
bundle/ale/ale_linters/haskell/hie.vim                                                                    23  Makefile:7: recipe for target 'test_coverage' failed
Error: Process completed with exit code 2.
```

**nvim nigltly:**

```
bundle/ale/ale_linters/eruby/erubi.vim                                                                    17     17     0%
Traceback (most recent call last):
bundle/ale/ale_linters/eruby/erubis.vim                                                                   12     12     0%
  File "/home/runner/.local/bin/covimerage", line 8, in <module>
bundle/ale/ale_linters/eruby/ruumba.vim                                                                   41     41     0%
    sys.exit(main())
bundle/ale/ale_linters/fish/fish.vim                                                                      36     36     0%
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
bundle/ale/ale_linters/fortran/gcc.vim                                                                    43     43     0%
    return self.main(*args, **kwargs)
bundle/ale/ale_linters/fortran/language_server.vim                                                        12     12     0%
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
bundle/ale/ale_linters/fountain/proselint.vim                                                              6      6     0%
    rv = self.invoke(ctx)
bundle/ale/ale_linters/fuse/fusionlint.vim                                                                22     22     0%
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
bundle/ale/ale_linters/gitcommit/gitlint.vim                                                              31     31     0%
    return _process_result(sub_ctx.command.invoke(sub_ctx))
bundle/ale/ale_linters/glsl/glslang.vim                                                                   23     23     0%
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
bundle/ale/ale_linters/glsl/glslls.vim                                                                    18     18     0%
    return ctx.invoke(self.callback, **ctx.params)
bundle/ale/ale_linters/go/bingo.vim                                                                       20     20     0%
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
bundle/ale/ale_linters/go/gobuild.vim                                                                     33     33     0%
    return callback(*args, **kwargs)
bundle/ale/ale_linters/go/gofmt.vim                                                                       10     10     0%
bundle/ale/ale_linters/go/golangci_lint.vim                                                               39     39     0%
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
bundle/ale/ale_linters/go/golint.vim                                                                      14     14     0%
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/cli.py", line 192, in run
bundle/ale/ale_linters/go/gometalinter.vim                                                                39     39     0%
    **report_opts)
bundle/ale/ale_linters/go/gopls.vim                                                                       22     22     0%
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
bundle/ale/ale_linters/go/gosimple.vim                                                                    11     11     0%
    return callback(*args, **kwargs)
bundle/ale/ale_linters/go/gotype.vim                                                                      13     13     0%
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
bundle/ale/ale_linters/go/govet.vim                                                                       18     18     0%
    return f(get_current_context(), *args, **kwargs)
bundle/ale/ale_linters/go/langserver.vim                                                                  19     19     0%
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/cli.py", line 278, in report
bundle/ale/ale_linters/go/revive.vim                                                                      14     14     0%
    skip_covered=skip_covered,
bundle/ale/ale_linters/go/staticcheck.vim                                                                 23     23     0%
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/coveragepy.py", line 71, in wrapper
bundle/ale/ale_linters/graphql/eslint.vim                                                                  6      6     0%
    return f(*args, **kwargs)
bundle/ale/ale_linters/graphql/gqlint.vim                                                                 10     10     0%
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/coveragepy.py", line 129, in report
bundle/ale/ale_linters/hack/hack.vim                                                                      13     13     0%
    omit=omit, skip_covered=skip_covered)
bundle/ale/ale_linters/hack/hhast.vim                                                                     23     23     0%
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/control.py", line 1041, in report
bundle/ale/ale_linters/haml/hamllint.vim                                                                  32     32     0%
    return reporter.report(morfs, outfile=file)
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/summary.py", line 143, in report
    writeout(line[0])
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/summary.py", line 35, in writeout
    outfile.write(line.rstrip())
BlockingIOError: [Errno 11] write could not complete without blocking
bundle/ale/ale_linters/handlebars/embertemplatelint.vim                                                   43     43     0%
bundle/ale/ale_linters/haskell/cabal_ghc.vim                                                              14     14     0%
bundle/ale/ale_linters/haskell/ghc.vim                                                                    12     12     0%
bundle/ale/ale_linters/haskell/ghc_mod.vim                                                                12     12     0%
bundle/ale/ale_linters/haskell/hdevtools.vim                                                              13     13     0%
make: *** [test_coverage] Error 1
bundle/ale/ale_linters/haskell/hie.vim                                                                    23  Makefile:7: recipe for target 'test_coverage' failed
Error: Process completed with exit code 2.
```

**nvim v0.4.3:**

```
bundle/ale/ale_linters/haskell/hdevtools.vim                                                              13     13     0%
Traceback (most recent call last):
  File "/home/runner/.local/bin/covimerage", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/cli.py", line 192, in run
    **report_opts)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/cli.py", line 278, in report
    skip_covered=skip_covered,
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/coveragepy.py", line 71, in wrapper
    return f(*args, **kwargs)
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/coveragepy.py", line 129, in report
    omit=omit, skip_covered=skip_covered)
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/control.py", line 1041, in report
    return reporter.report(morfs, outfile=file)
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/summary.py", line 143, in report
    writeout(line[0])
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/summary.py", line 35, in writeout
    outfile.write(line.rstrip())
BlockingIOError: [Errno 11] write could not complete without blocking
make: *** [test_coverage] Error 1
bundle/ale/ale_linters/haskell/hie.vim                                                                    23  Makefile:7: recipe for target 'test_coverage' failed
Error: Process completed with exit code 2.
```

**nvim v0.4.0:**

```
bundle/ale/ale_linters/eruby/erubis.vim                                                                   12     12     0%
  File "/home/runner/.local/bin/covimerage", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/cli.py", line 192, in run
    **report_opts)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/cli.py", line 278, in report
    skip_covered=skip_covered,
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/coveragepy.py", line 71, in wrapper
    return f(*args, **kwargs)
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/coveragepy.py", line 129, in report
    omit=omit, skip_covered=skip_covered)
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/control.py", line 1041, in report
    return reporter.report(morfs, outfile=file)
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/summary.py", line 143, in report
    writeout(line[0])
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/summary.py", line 35, in writeout
    outfile.write(line.rstrip())
BlockingIOError: [Errno 11] write could not complete without blocking
bundle/ale/ale_linters/eruby/ruumba.vim                                                                   41     41     0%
bundle/ale/ale_linters/fish/fish.vim                                                                      36     36     0%
bundle/ale/ale_linters/fortran/gcc.vim                                                                    43     43     0%
bundle/ale/ale_linters/fortran/language_server.vim                                                        12     12     0%
bundle/ale/ale_linters/fountain/proselint.vim                                                              6      6     0%
bundle/ale/ale_linters/fuse/fusionlint.vim                                                                22     22     0%
bundle/ale/ale_linters/gitcommit/gitlint.vim                                                              31     31     0%
bundle/ale/ale_linters/glsl/glslang.vim                                                                   23     23     0%
bundle/ale/ale_linters/glsl/glslls.vim                                                                    18     18     0%
bundle/ale/ale_linters/go/bingo.vim                                                                       20     20     0%
bundle/ale/ale_linters/go/gobuild.vim                                                                     33     33     0%
bundle/ale/ale_linters/go/gofmt.vim                                                                       10     10     0%
bundle/ale/ale_linters/go/golangci_lint.vim                                                               39     39     0%
bundle/ale/ale_linters/go/golint.vim                                                                      14     14     0%
bundle/ale/ale_linters/go/gometalinter.vim                                                                39     39     0%
bundle/ale/ale_linters/go/gopls.vim                                                                       22     22     0%
bundle/ale/ale_linters/go/gosimple.vim                                                                    11     11     0%
bundle/ale/ale_linters/go/gotype.vim                                                                      13     13     0%
bundle/ale/ale_linters/go/govet.vim                                                                       18     18     0%
bundle/ale/ale_linters/go/langserver.vim                                                                  19     19     0%
bundle/ale/ale_linters/go/revive.vim                                                                      14     14     0%
bundle/ale/ale_linters/go/staticcheck.vim                                                                 23     23     0%
bundle/ale/ale_linters/graphql/eslint.vim                                                                  6      6     0%
bundle/ale/ale_linters/graphql/gqlint.vim                                                                 10     10     0%
bundle/ale/ale_linters/hack/hack.vim                                                                      13     13     0%
bundle/ale/ale_linters/hack/hhast.vim                                                                     23     23     0%
bundle/ale/ale_linters/haml/hamllint.vim                                                                  32     32     0%
bundle/ale/ale_linters/handlebars/embertemplatelint.vim                                                   43     43     0%
bundle/ale/ale_linters/haskell/cabal_ghc.vim                                                              14     14     0%
bundle/ale/ale_linters/haskell/ghc.vim                                                                    12     12     0%
bundle/ale/ale_linters/haskell/ghc_mod.vim                                                                12     12     0%
bundle/ale/ale_linters/haskell/hdevtools.vim                                                              13     13     0%
make: *** [test_coverage] Error 1
bundle/ale/ale_linters/haskell/hie.vim                                                                    23  Makefile:7: recipe for target 'test_coverage' failed
Error: Process completed with exit code 2.
```

**nvim v0.3.8:**

```
bundle/ale/ale_linters/haskell/hdevtools.vim                                                              13     13     0%
Traceback (most recent call last):
  File "/home/runner/.local/bin/covimerage", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/cli.py", line 192, in run
    **report_opts)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/cli.py", line 278, in report
    skip_covered=skip_covered,
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/coveragepy.py", line 71, in wrapper
    return f(*args, **kwargs)
  File "/home/runner/.local/lib/python3.6/site-packages/covimerage/coveragepy.py", line 129, in report
    omit=omit, skip_covered=skip_covered)
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/control.py", line 1041, in report
    return reporter.report(morfs, outfile=file)
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/summary.py", line 143, in report
    writeout(line[0])
  File "/home/runner/.local/lib/python3.6/site-packages/coverage/summary.py", line 35, in writeout
    outfile.write(line.rstrip())
BlockingIOError: [Errno 11] write could not complete without blocking
make: *** [test_coverage] Error 1
bundle/ale/ale_linters/haskell/hie.vim                                                                    23  Makefile:7: recipe for target 'test_coverage' failed
Error: Process completed with exit code 2.
```

**Comment by wsdjeg** [comment] 2021-08-11 05:11
I want to ignore bundle direcort, and I found:

```
def build_vim_profile_args(profile_fname, sources):
    args = ['--cmd', 'profile start %s' % profile_fname]
    for source in sources:
        if os.path.isdir(source):
            pattern = '%s/*'
        else:
            pattern = '%s'
        args += ['--cmd', 'profile! file %s' % (pattern % source)]
    return args
```

so how can I build ares?

I found the default args is:

```
/home/wsdjeg/.local/bin/covimerage run nvim -Nu test/vimrc -c 'Vader! test/**'
Running cmd: nvim -Nu test/vimrc -c 'Vader! test/**' --cmd 'profile start /tmp/covimerage.profile.zwckeW' --cmd 'profile! file ./*' (in /home/wsdjeg/.SpaceVim)
```

**Comment by blueyed** [comment] 2021-09-12 20:37
As for the original/first comment the error appears to be commonly (via coverage.py):

> BlockingIOError: [Errno 11] write could not complete without blocking

Any update on that?  Maybe it is / was due to how it tried to write output, possible to stdout/stderr?

**Comment by blueyed** [comment] 2021-09-12 20:38
As for the second question, `args` is everything after `coverage run`: https://github.com/blueyed/covimerage/blob/4a4ddc5b5050115e48c35c12c6f42eb24bf195e6/covimerage/cli.py#L139-L147

**Comment by blueyed** [comment] 2021-09-12 20:39
Let's close this as duplicate of #94.

**Closed by blueyed** 2021-09-12 20:39 UTC
